### ISSUE TITLE
Disable Fortran not working

### ISSUE THREAD

**Issue by abhinavvishnu** [GlobalArrays/ga#30] opened 2017-04-10 16:46 UTC
Hi,

With the new (5.6) GA there seems to be a small glitch when switching off Fortran, e.g.: 

./configure --prefix=${HOME}/ga-install --disable-f77 MPICC=mpicc MPICXX=mpicxx 

worked with 5.5 but with 5.6 this gives: 

configure: error: conditional "F77_INTEL_NO_INLINE" was never defined. 
Usually this means the macro was only invoked conditionally. 

The F77_INTEL_NO_INLINE test seems to be new to 5.6, perhaps it just needs a default value for --disable-f77 case? 

Best wishes, 

Andy

**Comment by jeffdaily** [comment] 2017-04-26 23:10
This should be fixed soon for hotfix/5.6.1.  Should we add a travis-ci test for `--disable-f77`?  It would have caught this.

**Comment by jeffhammond** [comment] 2017-04-26 23:23
+1 to testing everything you want to work 😄

**Comment by ajmay81** [comment] 2017-04-29 11:24
I can confirm configure now passes with --disable-f77 on the hotfix/5.6.1 branch, however make fails near the end with:

    /bin/sh ./libtool  --tag=F77   --mode=link              -version-info 1:0:0  -o libga.la -rpath /nfs/home_theochem/may/new-mpi3/ga-mvapich2/lib compat/random.lo ma/error.lo ma/f2c.lo ma/ma.lo ma/string-util.lo ma/table.lo  LinAlg/lapack+blas/xgemm.lo global/src/base.lo global/src/capi.lo global/src/collect.lo global/src/datatypes.lo global/src/decomp.lo global/src/DP.lo global/src/elem_alg.lo global/src/fapi.lo global/src/ga_diag_seqc.lo global/src/ga_malloc.lo global/src/ga_solve_seq.lo global/src/ga_symmetr.lo global/src/ga_trace.lo global/src/ghosts.lo global/src/global.nalg.lo global/src/global.npatch.lo global/src/global.periodic.lo global/src/global.util.lo global/src/hsort.scat.lo global/src/matmul.lo global/src/matrix.lo global/src/nbutil.lo global/src/onesided.lo global/src/peigstubs.lo global/src/sclstubs.lo global/src/select.lo global/src/sparse.lo       pario/dra/buffers.lo pario/dra/capi.lo pario/dra/disk.arrays.lo pario/dra/disk.param.lo pario/dra/env.lo pario/dra/fortran.lo pario/dra/patch.util.lo pario/eaf/eaf.lo pario/eaf/eaf_f2c.lo pario/elio/elio.lo pario/elio/stat.lo pario/sf/sf_capi.lo pario/sf/sf_fortran.lo pario/sf/shared.files.lo  gaf2c/gaf2c.lo gaf2c/drand.lo  tcgmsg/capi.lo tcgmsg/fapi.lo tcgmsg/tcgmsg-mpi/checkbyte.lo tcgmsg/tcgmsg-mpi/clustercheck.lo tcgmsg/tcgmsg-mpi/collect.lo tcgmsg/tcgmsg-mpi/drand48.lo tcgmsg/tcgmsg-mpi/evlog.lo tcgmsg/tcgmsg-mpi/evon.lo tcgmsg/tcgmsg-mpi/llog.lo tcgmsg/tcgmsg-mpi/misc.lo tcgmsg/tcgmsg-mpi/niceftn.lo tcgmsg/tcgmsg-mpi/nxtval-armci.lo tcgmsg/tcgmsg-mpi/p2p.lo tcgmsg/tcgmsg-mpi/pbeginf.lo tcgmsg/tcgmsg-mpi/pfilecopy.lo tcgmsg/tcgmsg-mpi/sizeof.lo         comex/libarmci.la    
    Usage: /nfs/home_theochem/may/new-mpi3/ga/libtool [OPTION]... [MODE-ARG]...
    Try 'libtool --help' for more information.
    libtool:   error: unrecognised option: '-ersion-info'

which I'm currently working around with:

    make libga_la_LINK='$(LINK)'

**Comment by jeffdaily** [comment] 2017-05-02 21:57
I can't reproduce this error, but I wonder if it has something to do with a recent change to the autogen.sh script.

Starting at the comment `# patch ltmain.sh for special intel -mkl flag` in autogen.sh, comment out the next for loop and rerun autogen.sh, configure, and build.

**Comment by ajmay81** [comment] 2017-05-03 12:24
I don't think it's related, certainly commenting the for loop didn't help. I did some more digging and discovered that this entirely depends upon whether there is mpif90 in PATH or not, even though --disable-f77 is given. i.e.:

    ./configure --prefix=${HOME}/ga-install --disable-f77 MPICC=mpicc MPICXX=mpicxx
    make

gives the error if `which mpif90` (and perhaps `mpif77` etc.) is false, adding:

    export PATH="/path/to/mpif90/bin:${PATH}"

and the same configure and make then it works, and you see in the make output that failed before `mpif90` is referenced, which can't be right for --disable-f77:

    /bin/sh ./libtool  --tag=F77   --mode=link mpif90             -version-info 1:0:0  -o libga.la -rpath /nfs/home_theochem/may/new-mpi3/ga-mvapich2/lib compat/random.lo ma/error.lo ma/f2c.lo ma/ma.lo ma/string-util.lo ma/table.lo  LinAlg/lapack+blas/xgemm.lo global/src/base.lo global/src/capi.lo global/src/collect.lo global/src/datatypes.lo global/src/decomp.lo global/src/DP.lo global/src/elem_alg.lo global/src/fapi.lo global/src/ga_diag_seqc.lo global/src/ga_malloc.lo global/src/ga_solve_seq.lo global/src/ga_symmetr.lo global/src/ga_trace.lo global/src/ghosts.lo global/src/global.nalg.lo global/src/global.npatch.lo global/src/global.periodic.lo global/src/global.util.lo global/src/hsort.scat.lo global/src/matmul.lo global/src/matrix.lo global/src/nbutil.lo global/src/onesided.lo global/src/peigstubs.lo global/src/sclstubs.lo global/src/select.lo global/src/sparse.lo       pario/dra/buffers.lo pario/dra/capi.lo pario/dra/disk.arrays.lo pario/dra/disk.param.lo pario/dra/env.lo pario/dra/fortran.lo pario/dra/patch.util.lo pario/eaf/eaf.lo pario/eaf/eaf_f2c.lo pario/elio/elio.lo pario/elio/stat.lo pario/sf/sf_capi.lo pario/sf/sf_fortran.lo pario/sf/shared.files.lo  gaf2c/gaf2c.lo gaf2c/drand.lo  tcgmsg/capi.lo tcgmsg/fapi.lo tcgmsg/tcgmsg-mpi/checkbyte.lo tcgmsg/tcgmsg-mpi/clustercheck.lo tcgmsg/tcgmsg-mpi/collect.lo tcgmsg/tcgmsg-mpi/drand48.lo tcgmsg/tcgmsg-mpi/evlog.lo tcgmsg/tcgmsg-mpi/evon.lo tcgmsg/tcgmsg-mpi/llog.lo tcgmsg/tcgmsg-mpi/misc.lo tcgmsg/tcgmsg-mpi/niceftn.lo tcgmsg/tcgmsg-mpi/nxtval-armci.lo tcgmsg/tcgmsg-mpi/p2p.lo tcgmsg/tcgmsg-mpi/pbeginf.lo tcgmsg/tcgmsg-mpi/pfilecopy.lo tcgmsg/tcgmsg-mpi/sizeof.lo          armci/libarmci.la

**Comment by jeffdaily** [comment] 2017-05-03 16:35
Thank you for the detailed reproducer.  I was now able to reproduce this exact behavior on my mac by removing mpif90 from my $PATH.  Looking at this now.

**Comment by jeffdaily** [comment] 2017-05-03 16:59
Fixed in a6a4ae18a54f744f225018894284c7a43876cf10.

Due to fortran source files listed in libga_la_SOURCES, automake selected the fortran linker even when the fortran linker didn't exist or was explicitly disabled by the user (--disable-f77). We now override libga_la_LINK based on whether fortran is enabled.

**Comment by ajmay81** [comment] 2017-05-03 17:42
Thanks very much, --disable-f77 is now working correctly for me on hotfix/5.6.1 branch.

**Closed** 2017-05-26 18:15 UTC
